-- ================================================================
-- 05_extract_raw_data.sql — Production Data Extraction Query
-- ================================================================
-- PURPOSE:
--   This is the query that DataExtractor.run() executes via Python.
--   It joins employees + sales + customers to produce raw-data.csv.
--   raw-data.csv is the input to Module 05 ETL.
--
-- WHY THIS QUERY EXISTS:
--   The database stores data efficiently in separate tables.
--   Analytics and ML need one flat table with all columns together.
--   This "denormalisation" step is what data extraction means.
--
-- THE DATA IS INTENTIONALLY MESSY:
--   After the seed scripts ran, the database has:
--     - NULL salaries (3%)
--     - NULL performance_ratings (4%)
--     - Negative salaries (5 rows)
--     - Extreme salaries (1 row with £2.5M)
--     - years_experience = 99 (4 rows — system default for unknown)
--   Module 05 ETL will detect and fix these problems.
--   We leave them in the extraction deliberately.
--
-- CHANGE INDUSTRY BEFORE RUNNING:
--   The {{INDUSTRY}} placeholder is replaced by Python with the
--   actual industry schema name from config.py.
-- ================================================================

SELECT
    -- ── Employee core information ──────────────────────────────────
    e.employee_id,
    e.first_name,
    e.last_name,
    e.email,
    e.department,
    e.salary,                    -- may be NULL (data quality issue)
    e.hire_date,
    e.performance_rating,        -- may be NULL (data quality issue)
    e.years_experience,          -- may be 99 (system default for unknown)
    e.city,                      -- may be NULL for remote workers
    e.is_active,

    -- ── Sales aggregates (rolled up per employee) ─────────────────
    -- These come from the sales table via the aggregated subquery below
    emp_sales.num_sales,         -- total number of sales by this employee
    emp_sales.total_revenue,     -- total revenue generated by this employee
    emp_sales.avg_sale_value,    -- average value of each sale
    emp_sales.num_completed,     -- number of completed (not refunded/pending) sales

    -- ── Metadata ──────────────────────────────────────────────────
    '{industry}'::VARCHAR AS source_schema,   -- which schema this data came from
    NOW()::DATE           AS extracted_date   -- when the extraction ran

FROM {industry}.employees AS e

-- ── Left join: all employees, including those with no sales ───────
-- LEFT JOIN ensures employees with zero sales still appear in the output.
-- Their sales columns will be NULL (which ETL will handle).
LEFT JOIN (
    -- Subquery: aggregate sales to one row per employee
    SELECT
        employee_id,
        COUNT(*)                                    AS num_sales,
        ROUND(SUM(total_amount)::NUMERIC, 2)        AS total_revenue,
        ROUND(AVG(total_amount)::NUMERIC, 2)        AS avg_sale_value,
        COUNT(CASE WHEN status = 'Completed' THEN 1 END) AS num_completed
    FROM {industry}.sales
    GROUP BY employee_id
) AS emp_sales
    ON e.employee_id = emp_sales.employee_id

-- ── Order makes the CSV easier to read ────────────────────────────
ORDER BY e.department, e.employee_id;
